version: "3"
services:
  jackboxdiscordbot:
    build: .
    image: mikeactually/jackbox-discord:latest
    command: yarn start
    # environment:
    #  - NODE_ENV=production
    #  - GAMESLIST=PATH RELATIVE to ./src OR URL TO GAMES LIST
    #  - JACKBOXKEY=<PUT YOUR KEY HERE AND UNCOMMENT>
    #  - TOPGGKEY=<TOPGGKEY>
    #  - APPID=<APPIDHERE>
    #  - NEW_RELIC_LICENSE_KEY=<LICENSEKEYHERE>
    #  - NEW_RELIC_APP_NAME=<NRAPPNAMEHERE>
    env_file:
      - .env
